#!/usr/bin/env python3
"""Generate fixed fbank tables that match examples/hi_xiaowen/s0/torch2lite/fbank.cc."""

from __future__ import annotations

import argparse
import math
from pathlib import Path


DEFAULT_OUTPUT = Path(__file__).resolve().parent / "fbank_tables_fixed_config.h"
DEFAULT_SAMPLE_RATE = 16000
DEFAULT_FRAME_LENGTH = 400
DEFAULT_NUM_MEL_BINS = 80
DEFAULT_FFT_SIZE = 512
DEFAULT_LOW_FREQ = 20.0
DEFAULT_HIGH_FREQ = 8000.0
DEFAULT_FILTER_WIDTH = 256


def hz_to_mel(hz: float) -> float:
    return 1127.0 * math.log(1.0 + hz / 700.0)


def init_povey_window(window_size: int) -> list[float]:
    values = []
    for i in range(window_size):
        a = 2.0 * math.pi * i / (window_size - 1)
        values.append(pow(0.5 - 0.5 * math.cos(a), 0.85))
    return values


def init_mel_banks(sample_rate: int,
                   fft_size: int,
                   num_mel_bins: int,
                   low_freq: float,
                   high_freq: float,
                   max_filter_width: int) -> list[tuple[int, int, list[float]]]:
    num_fft_bins = fft_size // 2
    nyquist = sample_rate / 2.0
    if high_freq <= 0.0:
        high_freq += nyquist
    if high_freq > nyquist:
        high_freq = nyquist
    if not (0.0 <= low_freq < nyquist and 0.0 < high_freq <= nyquist and low_freq < high_freq):
        raise ValueError('invalid low/high frequency range')

    mel_low = hz_to_mel(low_freq)
    mel_high = hz_to_mel(high_freq)
    mel_step = (mel_high - mel_low) / (num_mel_bins + 1)
    fft_bin_width = float(sample_rate) / float(fft_size)

    filters: list[tuple[int, int, list[float]]] = []
    for i in range(num_mel_bins):
        left_mel = mel_low + i * mel_step
        center_mel = mel_low + (i + 1) * mel_step
        right_mel = mel_low + (i + 2) * mel_step

        start_bin = -1
        end_bin = -1
        dense_weights: list[float] = []

        for fft_bin in range(num_fft_bins):
            freq = fft_bin_width * fft_bin
            mel = hz_to_mel(freq)
            up_slope = (mel - left_mel) / (center_mel - left_mel)
            down_slope = (right_mel - mel) / (right_mel - center_mel)
            weight = min(up_slope, down_slope)
            if weight < 0.0:
                weight = 0.0
            if weight <= 0.0:
                continue
            if start_bin < 0:
                start_bin = fft_bin
            end_bin = fft_bin + 1
            dense_weights.append(weight)

        if start_bin < 0 or end_bin < 0:
            raise ValueError(f'failed to build mel filter {i}')

        filter_width = end_bin - start_bin
        if filter_width > max_filter_width:
            raise ValueError(
                f'filter {i} width {filter_width} exceeds max_filter_width={max_filter_width}')

        weights = dense_weights + [0.0] * (max_filter_width - filter_width)
        filters.append((start_bin, end_bin, weights))

    return filters


def format_float(value: float) -> str:
    return f'{value:.8f}f'


def format_array(values: list[float], indent: str, wrap: int = 8) -> str:
    lines = []
    for i in range(0, len(values), wrap):
        chunk = ', '.join(format_float(v) for v in values[i:i + wrap])
        lines.append(f'{indent}{chunk},')
    if lines:
        lines[-1] = lines[-1].rstrip(',')
    return '\n'.join(lines)


def generate_header(sample_rate: int,
                    frame_length: int,
                    num_mel_bins: int,
                    fft_size: int,
                    low_freq: float,
                    high_freq: float,
                    max_filter_width: int) -> str:
    window = init_povey_window(frame_length)
    filters = init_mel_banks(sample_rate, fft_size, num_mel_bins, low_freq, high_freq, max_filter_width)

    normalized_high_freq = high_freq
    if normalized_high_freq <= 0.0:
        normalized_high_freq += sample_rate / 2.0
    if normalized_high_freq > sample_rate / 2.0:
        normalized_high_freq = sample_rate / 2.0

    filter_name = f'kMelFilters_{sample_rate // 1000}k_fft{fft_size}_bins{num_mel_bins}'
    window_name = f'kPoveyWindow_{frame_length}'

    lines = [
        '/* Auto-generated by examples/hi_xiaowen/s0/torch2lite/gen_fbank_tables.py. Do not edit. */',
        f'/* Config: sample_rate={sample_rate} fft_size={fft_size} frame_length={frame_length} num_mel_bins={num_mel_bins} */',
        '',
        '#ifndef FBANK_TABLES_FIXED_CONFIG_H_',
        '#define FBANK_TABLES_FIXED_CONFIG_H_',
        '',
        '#include "fbank.h"',
        '',
        f'#define FBANK_TABLE_SAMPLE_RATE {sample_rate}',
        f'#define FBANK_TABLE_FRAME_LENGTH {frame_length}',
        f'#define FBANK_TABLE_NUM_MEL_BINS {num_mel_bins}',
        f'#define FBANK_TABLE_FFT_SIZE {fft_size}',
        f'#define FBANK_TABLE_LOW_FREQ {low_freq:.6f}f',
        f'#define FBANK_TABLE_HIGH_FREQ {normalized_high_freq:.6f}f',
        '',
        f'/* Povey window, length = {frame_length} */',
        f'static const float {window_name}[FBANK_TABLE_FRAME_LENGTH] = {{',
        format_array(window, '  '),
        '};',
        '',
        '/* SparseMelFilter with zero-padded unused weight slots. */',
        f'static const SparseMelFilter {filter_name}[FBANK_TABLE_NUM_MEL_BINS] = {{',
    ]

    for start_bin, end_bin, weights in filters:
        weight_values = ', '.join(format_float(v) for v in weights)
        lines.append(f'  {{ {start_bin}, {end_bin}, {{ {weight_values} }} }},')

    lines.extend([
        '};',
        '',
        f'#define FBANK_PRECOMPUTED_WINDOW {window_name}',
        f'#define FBANK_PRECOMPUTED_MEL_FILTERS {filter_name}',
        '',
        '#endif /* FBANK_TABLES_FIXED_CONFIG_H_ */',
        '',
    ])
    return '\n'.join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description='Generate fixed fbank tables for MCU precomputed mode.')
    parser.add_argument('--sample-rate', type=int, default=DEFAULT_SAMPLE_RATE)
    parser.add_argument('--frame-length', type=int, default=DEFAULT_FRAME_LENGTH,
                        help='Frame length in samples, not milliseconds.')
    parser.add_argument('--num-mel-bins', type=int, default=DEFAULT_NUM_MEL_BINS)
    parser.add_argument('--fft-size', type=int, default=DEFAULT_FFT_SIZE)
    parser.add_argument('--low-freq', type=float, default=DEFAULT_LOW_FREQ)
    parser.add_argument('--high-freq', type=float, default=DEFAULT_HIGH_FREQ)
    parser.add_argument('--max-filter-width', type=int, default=DEFAULT_FILTER_WIDTH)
    parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    header = generate_header(
        sample_rate=args.sample_rate,
        frame_length=args.frame_length,
        num_mel_bins=args.num_mel_bins,
        fft_size=args.fft_size,
        low_freq=args.low_freq,
        high_freq=args.high_freq,
        max_filter_width=args.max_filter_width,
    )
    args.output.write_text(header)
    print(args.output)


if __name__ == '__main__':
    main()
